### PR TITLE
Versions Updated

### PR DESCRIPTION
**Pull request by extmkv**

### CODE REVIEW

**Comment by jzeferino** [comment]
@extmkv any problem updating versions?

**Comment by extmkv** [comment]
Yes.

**Comment by jzeferino** [comment]
@extmkv this experimental commits should be done in https://github.com/massivedisaster/ADAL/blob/72380ee6fadf423f2f149762abdda2ba0be115b2/.travis.yml#L43. Don't merge this PR since it has a lot of unnecessary commits. Instead, after the fix, create a new branch from develop with the fix commit.

**Comment by jzeferino** [comment]
@extmkv why API 26?

**Pull request closed without merging**
