### PR TITLE
Feature/checkstyle

### PR DESCRIPTION
**Pull request by Andrer757**

### CODE REVIEW

**Review by jzeferino — COMMENTED** [review]
LGTM. @extmkv can you fix the current style violations? You could do that in this same branch.

**Comment by jzeferino** [comment]
@Andrer757 please pay attention to the commit email.

**Comment by Andrer757** [comment]
@jzeferino yes I detected that, and thats why my last commit is with the correct email. I already configured my PC to never have this problem again.

**Comment by jzeferino** [comment]
@Andrer757 ok. before we release the 0.2.0 I will run the script to change all the wrong emails.

**Comment by jzeferino** [comment]
Regarding this two types of errors, I suggest that we remove them from the configuration file.

https://pmd.github.io/pmd-5.6.1/pmd-java/rules/java/design.html#AccessorMethodGeneration
https://pmd.github.io/pmd-5.6.1/pmd-java/rules/java/design.html#UncommentedEmptyMethodBody

 @massivedisaster/adal-dev what do you guys think?

**Comment by jzeferino** [comment]
I've added application-state validadtions.

**Comment by jzeferino** [comment]
Closes #53.

**Pull request merged**
