### PR TITLE
Added license files to idea folder.

### PR DESCRIPTION
**Pull request by jzeferino**

### CODE REVIEW

**Comment by extmkv** [comment]
Removed the hardcoded project name from the profile_settings.

**Comment by jzeferino** [comment]
@extmkv let me test it locally.

**Comment by extmkv** [comment]
I did the test locally to check, before the commit ...

**Comment by jzeferino** [comment]
@extmkv I checked it locally and you break it.
The `profiles_settings.xml` stores the currently used license. In our specific case the license name is  `ADAL GNU Lesser General Public License` we can't use `$project.name` there because it wont be parsed. It must be `ADAL GNU Lesser General Public License`.

**Pull request merged**
